spring:
  application:
    name: ticket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: support
    password: PASSWORD
    url: jdbc:mysql://localhost:3308/ticket
    name: support
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  feign:
    client:
      config:
        default:
          connectTimeout: 60000
          readTimeout: 10000

