spring:
  application:
    name: support-ticket-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: support
    password: PASSWORD
    url: jdbc:mysql://localhost:3306/support
    name: verde
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: message